@echo off
echo Deleting old dist folder...
if exist dist rmdir /s /q dist

echo Building with PyInstaller...
pyinstaller --clean build.spec

echo Copying bizhawk-connector to dist...
xcopy /E /I /Y bizhawk-connector dist\bizhawk-connector